let b2b_enquiries;_a29‍.x([["findAllUsers",()=>findAllUsers],["findWithContactName",()=>findWithContactName],["findWithWebsiteName",()=>findWithWebsiteName],["updateUsingWebsiteName",()=>updateUsingWebsiteName],["deleteUsingID",()=>deleteUsingID],["savingQueriesInDatabase",()=>savingQueriesInDatabase]]);_a29‍.w("../models/enquiries",[["default",["b2b_enquiries"],function(v){b2b_enquiries=v}]]);

       const findAllUsers = async (req, res) => {
    _a29‍.g.console.log(req.body);
    // For finding all documents in user
    try {
        await b2b_enquiries.find({}).limit(10).then(users => {
                if (!users) {
                    return res.status(404).json({
                        success: false,
                        message: 'Users not found'
                    })
                } else {
                    _a29‍.g.console.log(users)
                    return res.status(200).json({
                        success: true,
                        data: users
                    })
                }
            })
    } catch (err) {
        _a29‍.g.console.log(err)
        return res.status(500).json({
            success: false,
            message: 'Error occured in finding all documents ' + err
        })
    }
}

       const findWithContactName = async (req, res) => {
    // For finding all documents with specific contact Name
    try{
        await b2b_enquiries.find({contactName: "Harsh"}).then(users => {
            if(!users){
                return res.status(404).json({
                    success: false,
                    message: "User not found"
                })
            }else{
                _a29‍.g.console.log(users);
                res.send(200).json({
                    success: true,
                    data: users
                })
            }
        }) 
    }catch (err) {
        _a29‍.g.console.log(err)
        return res.status(500).json({
            success: false,
            message: "Error occured in finding a document by Contact Name " + err
        })
    }
}

       const findWithWebsiteName = async (req, res) => {
    //For finding a document with specific Website Name
    try{
        await b2b_enquiries.findOne({websiteName: "abc.com"}).then((response) => {
            if(!response){
                return res.status(404).send("Website Name not found")
            }else {
                _a29‍.g.console.log(response);
                res.send(200).json({
                    success: true,
                    data: response
                })
            }
        })
    }
    catch(err){
        _a29‍.g.console.log(err);
        res.status(500).json({
            success: false,
            message: "Error occured in finding a document by Website Name "+ err
        })
    }
}

       const updateUsingWebsiteName = async (req, res) => {
    // Update a document by its Website Name
    try{
        await b2b_enquiries.updateOne({websiteName: "abc.com"}, { $set: {phoneNumber: 8734787426}}).then((response) => {
            _a29‍.g.console.log(response);
            res.send(200).json({
                success: true,
                data: response
            })
        })
    }
    catch(err){
        _a29‍.g.console.log(err);
        res.status(500).json({
            success: false,
            message: "Error occured in updating document "+ err
        })
    }
}

       const deleteUsingID = async (req, res) => {
    // For Deleting document of specific id
    try{
        const afterDeletion = await b2b_enquiries.queries.deleteOne({_id: isObjectId("9834945983408")});
        _a29‍.g.console.log(afterDeletion);
    }
    catch(err){
        _a29‍.g.console.log(err)
        return res.status(500).json({
            success: false,
            message: "Error occured while deleting " + err
        })
    }
}

       const savingQueriesInDatabase = async (req, res) => {
    //For saving user object into b2b_enquiries
    const user = new b2b_enquiries(req.body);
    _a29‍.g.console.log("User created ", user);
    try{
        user.save().then((result) => {
            _a29‍.g.console.log(result);
        })
    }
    catch(err){
        _a29‍.g.console.log(err);
        res.status(500).send("Error occured while saving the data");
    }
    

}